# Generated by Django 4.1.6 on 2023-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='blank.jpg', upload_to='cover_images'),
        ),
    ]
