# Generated by Django 4.1.6 on 2023-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_profile_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(blank=True, upload_to='cover_images'),
        ),
    ]
