# Generated by Django 4.1.6 on 2023-02-19 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_alter_cover_post_id_alter_cover_post_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover_post',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cover_post',
            old_name='user1',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cover_post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
