# Generated by Django 4.1.6 on 2023-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0010_rename_image1_cover_post_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover_Post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coverimg',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default=2, upload_to='cover_images'),
            preserve_default=False,
        ),
    ]
