# Generated by Django 4.1.6 on 2023-02-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_delete_cover_post_remove_profile_coverimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
